sudo: false
cache: bundler
language: ruby
rvm:
  - 2.3.5
  - 2.4.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
branches:
  only:
    - master
before_install:
- if [[ $BUNDLE_GEMFILE == *master.gemfile ]]; then gem update --system; fi
- gem --version
- gem install bundler
- bundle --version
script: bundle exec rake spec
